import { Component } from '@angular/core';
import { ToastrService } from 'ngx-toastr';
import { BuggyBackendService } from 'src/app/autogenerated/api.client.generated';
import { handleError } from '../custom-operators';

@Component({
  selector: 'app-test-error',
  templateUrl: './test-error.component.html',
  styleUrls: ['./test-error.component.scss'],
  providers: [BuggyBackendService],
})
export class TestErrorComponent {
  public validationErrors: any;

  public constructor(
    private readonly errorBackendService: BuggyBackendService,
    private readonly toastr: ToastrService,
  ) {}

  public get404Error(): void {
    this.errorBackendService.getNotFoundRequestById().pipe(handleError(this.toastr)).subscribe();
  }

  public get500Error(): void {
    this.errorBackendService.getServerError().pipe(handleError(this.toastr)).subscribe();
  }

  public get400Error(): void {
    this.errorBackendService.getBadRequest().pipe(handleError(this.toastr)).subscribe();
  }

  public get400ValidationError(): void {
    const test: any = 'four';

    this.errorBackendService.getNotFoundRequestValidation(test).pipe(handleError(this.toastr)).subscribe();
  }
}
