import { Injectable } from '@angular/core';
import { ToastrService } from 'ngx-toastr';
import { map, Observable } from 'rxjs';
import {
  DeliveryMethodViewModel,
  Order,
  OrdersBackendService,
  OrderViewModel,
} from '../autogenerated/api.client.generated';
import { handleError } from '../core/custom-operators';

@Injectable({
  providedIn: 'root',
})
export class CheckoutService {
  public constructor(
    private readonly orderBackendService: OrdersBackendService,
    private readonly toastr: ToastrService,
  ) {}

  public createOrder(order: OrderViewModel): Observable<Order> {
    return this.orderBackendService.createOrder(order);
  }

  public getDeliveryMethods(): Observable<DeliveryMethodViewModel[]> {
    return this.orderBackendService.getDeliveryMethods().pipe(
      map((dm: DeliveryMethodViewModel[]) => {
        return dm.sort((a, b) => b.price - a.price);
      }),

      handleError(this.toastr),
    );
  }
}
