import { AfterViewInit, Component, ElementRef, Input, OnDestroy, ViewChild } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { NavigationExtras, Router } from '@angular/router';
import { ToastrService } from 'ngx-toastr';
import {
  CustomerBasketViewModel,
  ICustomerBasketViewModel,
  OrderViewModel,
} from 'src/app/autogenerated/api.client.generated';
import { BasketService } from 'src/app/basket/basket.service';
import { CheckoutService } from '../checkout.service';

declare let Stripe;

@Component({
  selector: 'app-checkout-payment',
  templateUrl: './checkout-payment.component.html',
  styleUrls: ['./checkout-payment.component.scss'],
})
export class CheckoutPaymentComponent implements AfterViewInit, OnDestroy {
  @Input() public checkoutForm: FormGroup;
  @ViewChild('cardNumber', { static: true }) public cardNumberElement: ElementRef;
  @ViewChild('cardExpiry', { static: true }) public cardExpiryElement: ElementRef;
  @ViewChild('cardCvc', { static: true }) public cardCvcElement: ElementRef;
  public cardErrors: any;
  public cardHandler = this.onChange.bind(this);
  public loading = false;
  public cardNumberValid = false;
  public cardExpiryValid = false;
  public cardCvcValid = false;
  private stripe: any;
  private cardNumber: any;
  private cardExpiry: any;
  private cardCvc: any;

  public constructor(
    private basketService: BasketService,
    private checkoutService: CheckoutService,
    private toastr: ToastrService,
    private router: Router,
  ) {}

  public ngAfterViewInit(): void {
    this.stripe = Stripe(
      'pk_test_51KqMJ7ApS2CQ3bzRrNFfMkz3qn9lLGprvOUVRObMfkBCB2cbhjmLcUO5lMGHzNIMvUs9RxNCNwBoIbhCM021IAeV00WWWxq9VF',
    );
    const elements = this.stripe.elements();

    this.cardNumber = elements.create('cardNumber');
    this.cardNumber.mount(this.cardNumberElement.nativeElement);
    this.cardNumber.addEventListener('change', this.cardHandler);

    this.cardExpiry = elements.create('cardExpiry');
    this.cardExpiry.mount(this.cardExpiryElement.nativeElement);
    this.cardExpiry.addEventListener('change', this.cardHandler);

    this.cardCvc = elements.create('cardCvc');
    this.cardCvc.mount(this.cardCvcElement.nativeElement);
    this.cardCvc.addEventListener('change', this.cardHandler);
  }

  public ngOnDestroy(): void {
    this.cardNumber.destroy();
    this.cardExpiry.destroy();
    this.cardCvc.destroy();
  }

  public onChange(event): void {
    if (event.error) {
      this.cardErrors = event.error.message;
    } else {
      this.cardErrors = null;
    }

    switch (event.elementType) {
      case 'cardNumber':
        this.cardNumberValid = event.complete;
        break;
      case 'cardExpiry':
        this.cardExpiryValid = event.complete;
        break;
      case 'cardCvc':
        this.cardCvcValid = event.complete;
        break;
    }
  }

  public async submitOrder(): Promise<void> {
    this.loading = true;
    const basket = this.basketService.getCurrentBasketValue();

    try {
      const createdOrder = await this.createOrder(basket);
      const paymentResult = await this.confirmPaymentWithStripe(basket);

      if (paymentResult.paymentIntent) {
        this.basketService.deleteBasket(basket);
        const navigationExtras: NavigationExtras = { state: createdOrder };
        this.router.navigate(['checkout/success'], navigationExtras);
      } else {
        this.toastr.error(paymentResult.error.message);
      }

      this.loading = false;
    } catch (error) {
      console.log(error);
      this.loading = false;
    }
  }

  private async confirmPaymentWithStripe(basket: ICustomerBasketViewModel): Promise<any> {
    return this.stripe.confirmCardPayment(basket.clientSecret, {
      payment_method: {
        card: this.cardNumber,
        billing_details: {
          name: this.checkoutForm.get('paymentForm').get('nameOnCard').value,
        },
      },
    });
  }

  private async createOrder(basket: CustomerBasketViewModel): Promise<any> {
    const orderToCreate = this.getOrderToCreate(basket);
    return this.checkoutService.createOrder(orderToCreate).toPromise();
  }

  private getOrderToCreate(basket: CustomerBasketViewModel): OrderViewModel {
    return new OrderViewModel({
      basketId: basket.id.toString(),
      deliveryMethodId: +this.checkoutForm.get('deliveryForm').get('deliveryMethod').value,
      shipToAddress: this.checkoutForm.get('addressForm').value,
    });
  }
}
