import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { CustomerBasketViewModel } from '../autogenerated/api.client.generated';
import { IBasketItem, IBasketTotals } from '../shared/models/basket';
import { BasketService } from './basket.service';

@Component({
  selector: 'app-basket',
  templateUrl: './basket.component.html',
  styleUrls: ['./basket.component.scss'],
})
export class BasketComponent implements OnInit {
  public basket$: Observable<CustomerBasketViewModel>;
  public basketTotals$: Observable<IBasketTotals>;

  public constructor(private basketService: BasketService) {}

  public ngOnInit(): void {
    this.basket$ = this.basketService.basket$;
    this.basketTotals$ = this.basketService.basketTotal$;
  }

  public removeBasketItem(item: IBasketItem): void {
    this.basketService.removeItemFromBasket(item);
  }

  public incrementItemQuantity(item: IBasketItem): void {
    this.basketService.incrementItemQuantity(item);
  }

  public decrementItemQuantity(item: IBasketItem): void {
    this.basketService.decrementItemQuantity(item);
  }
}
