import { Component, Input, OnChanges } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { IDeliveryMethodViewModel } from 'src/app/autogenerated/api.client.generated';
import { BasketService } from 'src/app/basket/basket.service';
import { IDeliveryMethod } from 'src/app/shared/models/deliveryMerhod';
import { CheckoutService } from '../checkout.service';

@Component({
  selector: 'app-checkout-delivery',
  templateUrl: './checkout-delivery.component.html',
  styleUrls: ['./checkout-delivery.component.scss'],
})
export class CheckoutDeliveryComponent implements OnChanges {
  @Input() public checkoutForm: FormGroup;
  public deliveryMethods: IDeliveryMethodViewModel[];

  public constructor(private checkoutService: CheckoutService, private basketService: BasketService) {}

  public ngOnChanges(): void {
    this.checkoutService.getDeliveryMethods().subscribe((dm: IDeliveryMethodViewModel[]) => {
      this.deliveryMethods = dm;
    });
  }

  public shippingPrice(deliveryMethod: IDeliveryMethod): void {
    this.basketService.setShippingPrice(deliveryMethod);
  }
}
