import { Component, OnInit } from '@angular/core';
import { IOrderDetailsViewModal } from '../autogenerated/api.client.generated';
import { OrdersService } from './orders.service';

@Component({
  selector: 'app-orders',
  templateUrl: './orders.component.html',
  styleUrls: ['./orders.component.scss'],
})
export class OrdersComponent implements OnInit {
  public orders: IOrderDetailsViewModal[];

  public constructor(private ordersService: OrdersService) {}

  public ngOnInit(): void {
    this.getOrders();
  }

  public getOrders(): void {
    this.ordersService.getOrdersForUser().subscribe((order: IOrderDetailsViewModal[]) => {
      this.orders = order;
    });
  }
}
