import { Injectable } from '@angular/core';
import { ToastrService } from 'ngx-toastr';
import { Observable } from 'rxjs';
import { OrderDetailsViewModal, OrdersBackendService } from '../autogenerated/api.client.generated';
import { handleError } from '../core/custom-operators';

@Injectable({
  providedIn: 'root',
})
export class OrdersService {
  public constructor(
    private readonly orderBackendService: OrdersBackendService,
    private readonly toastr: ToastrService,
  ) {}

  public getOrdersForUser(): Observable<OrderDetailsViewModal[]> {
    return this.orderBackendService.getOrdersForUser().pipe(handleError(this.toastr));
  }

  public getOrderDetailed(id: number): Observable<OrderDetailsViewModal> {
    return this.orderBackendService.getOrderByIdForUser(id).pipe(handleError(this.toastr));
  }
}
