import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import {
  IProductBrandViewModel,
  IProductDetailsViewModel,
  IProductTypeViewModel,
  ProductBrandViewModel,
  ProductTypeViewModel,
} from '../autogenerated/api.client.generated';
import { ShopParams } from '../shared/models/shopParams';
import { ShopService } from './shop.service';

@Component({
  selector: 'app-shop',
  templateUrl: './shop.component.html',
  styleUrls: ['./shop.component.scss'],
})
export class ShopComponent implements OnInit {
  @ViewChild('search') public searchTerm: ElementRef;
  public products: IProductDetailsViewModel[];
  public brands: IProductBrandViewModel[];
  public types: IProductTypeViewModel[];
  public totalCount: number;
  public shopParams: ShopParams;

  public sortOptions = [
    { name: 'Alphabetical', value: 'name' },
    { name: 'Price: Low to High', value: 'priceAsc' },
    { name: 'Price: High to Low', value: 'priceDesc' },
  ];

  public constructor(private shopService: ShopService) {
    this.shopParams = this.shopService.getShopParams();
  }

  public ngOnInit(): void {
    this.getProducts(true);
    this.getBrands();
    this.getTypes();
  }

  public getProducts(useCache = false): void {
    this.shopService.getProducts(useCache).subscribe((response) => {
      this.products = response.data;
      this.totalCount = response.count;
    });
  }

  public getBrands(): void {
    this.shopService.getBrands().subscribe((response) => {
      const all = new ProductBrandViewModel({ id: undefined, name: 'All' });
      this.brands = [all, ...response];
    });
  }

  public getTypes(): void {
    this.shopService.getTypes().subscribe((response) => {
      const all = new ProductTypeViewModel({ id: undefined, name: 'All' });
      this.types = [all, ...response];
    });
  }

  public onBrandSelected(brandId: number): void {
    const params = this.shopService.getShopParams();
    params.brandId = brandId;
    params.pageNumber = 1;
    this.shopService.setShopParams(params);
    this.getProducts();
  }

  public onTypeSelected(typeId: number): void {
    const params = this.shopService.getShopParams();
    params.typeId = typeId;
    params.pageNumber = 1;
    this.shopService.setShopParams(params);
    this.getProducts();
  }

  public onSortSelected(sort: string): void {
    const params = this.shopService.getShopParams();
    params.sort = sort;
    this.shopService.setShopParams(params);
    this.getProducts();
  }

  public onPageChanged(event: any): void {
    const params = this.shopService.getShopParams();
    if (params.pageNumber !== event) {
      params.pageNumber = event;
      this.shopService.setShopParams(params);
      this.getProducts(true);
    }
  }

  public onSearch(): void {
    const params = this.shopService.getShopParams();
    params.search = this.searchTerm.nativeElement.value;
    params.pageNumber = 1;
    this.shopService.setShopParams(params);
    this.getProducts();
  }

  public onReset(): void {
    this.searchTerm.nativeElement.value = '';
    this.shopParams = new ShopParams();
    this.shopService.setShopParams(this.shopParams);
    this.getProducts();
  }
}
